import os
import sys
import json
from price_option import price_option
from price_call_black_scholes import price_call_black_scholes


def implied_volatility(directory, strike, maturity):
    """
    Compute implied volatility from option price and model parameters. Implied volatility is the global volatility
    assuming the process has been generated by a geometric Brownian motion.

    Parameters
    ----------
    directory : str
        Path to directory containing simulation data.
    strike : float
        Option strike price.
    maturity : float
        Option maturity.
    """
    from scipy.optimize import brentq
    output_file_path = os.path.join(directory, "output.json")
    with open(output_file_path, "r") as f:
        output = json.load(f)
    risk_free_rate = output['model_params']['risk_free_rate']
    stock_price = output['initial_value'][0]
    call_price = price_option(directory=directory, strike=strike, maturity=maturity)[0]
    # Numerically solve for implied volatility using Black-Scholes formula as objective function
    objective_function = lambda sigma: price_call_black_scholes(stock_price=stock_price, strike=strike,
                                                                maturity=maturity, risk_free_rate=risk_free_rate,
                                                                sigma=sigma) - call_price
    implied_vol = brentq(objective_function, 1e-6, 10.0)
    print(f'Implied volatility: {implied_vol:.2f}')

    return implied_vol

if __name__ == "__main__":
    implied_volatility(sys.argv[1], float(sys.argv[2]), float(sys.argv[3]))
